project:
  type: website
  preview: 
    port: 8080
    navigate: false

website:
  title: "Blog do Tomorrow Positivo"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



