project:
  type: website
  preview: 
    port: 8080
    browser: false

website:
  navbar:
    logo: "/imagens/tomorrow_0_0.png"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/carolbalbs/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



