project:
  type: website
  preview: 
    port: 8080
    browser: false

website:
  favicon: "/imagens/favicon.png"
  navbar:
    logo: "/imagens/tomorrow_0_0.png"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/carolbalbs/blog_tomorrow
      - icon: instagram
        href: https://instagram.com/tomorrowufba
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



